-- Table: public.users

DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

COMMIT;


-- Table: public.default_categories

DROP TABLE IF EXISTS public.default_categories CASCADE;

CREATE TABLE IF NOT EXISTS public.default_categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    colour_hex character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT default_categories_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.default_categories
    OWNER to postgres;

COMMIT;

-- Table: public.categories

DROP TABLE IF EXISTS public.categories CASCADE;

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    colour_hex character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT fkghuylkwuedgl2qahxjt8g41kb FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.categories
    OWNER to postgres;

COMMIT;

-- Table: public.merchants

DROP TABLE IF EXISTS public.merchants CASCADE;

CREATE TABLE IF NOT EXISTS public.merchants
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    default_category_id integer,
    user_id integer,
    CONSTRAINT merchants_pkey PRIMARY KEY (id),
    CONSTRAINT fk2dkk3rw4qu9h0cm259k6ka10x FOREIGN KEY (default_category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fka759srj6ts95j9qh089b6gbei FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.merchants
    OWNER to postgres;

COMMIT;

-- Table: public.recurrences

DROP TABLE IF EXISTS public.recurrences CASCADE;

CREATE TABLE IF NOT EXISTS public.recurrences
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount double precision,
    description character varying(255) COLLATE pg_catalog."default",
    end_date timestamp without time zone,
    start_date timestamp without time zone,
    title character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT recurrences_pkey PRIMARY KEY (id),
    CONSTRAINT fkeclrv9jf5tuxcuccq9y7pbk77 FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recurrences
    OWNER to postgres;

-- Table: public.expenses

DROP TABLE IF EXISTS public.expenses CASCADE;

CREATE TABLE IF NOT EXISTS public.expenses
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount double precision,
    date timestamp without time zone,
    description character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    category_id integer,
    merchant_id integer,
    recurrence_id integer,
    CONSTRAINT expenses_pkey PRIMARY KEY (id),
    CONSTRAINT fkhpk0n2cbnfiuu5nrgl0ika3hq FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkjao23ohq935a4qrorwwsen0lr FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fklryw5q6a3s1v6k9wcirvau35p FOREIGN KEY (recurrence_id)
        REFERENCES public.recurrences (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkpvvyyytwh12xn9nxyhaoxu6vo FOREIGN KEY (merchant_id)
        REFERENCES public.merchants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.expenses
    OWNER to postgres;

COMMIT;

-- Table: public.budgets

DROP TABLE IF EXISTS public.budgets CASCADE;

CREATE TABLE IF NOT EXISTS public.budgets
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    month integer,
    year integer,
    user_id integer,
    CONSTRAINT budgets_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.budgets
    OWNER to postgres;

-- Table: public.budget_categories

DROP TABLE IF EXISTS public.budget_categories CASCADE;

CREATE TABLE IF NOT EXISTS public.budget_categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount real,
    budget_id integer,
    category_id integer,
    user_id integer,
    CONSTRAINT budget_categories_pkey PRIMARY KEY (id),
    CONSTRAINT fk7dnkp89rbhc1ygj79rxwunvu6 FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk7xdi9b13c0h6mpy55c0lvgs2w FOREIGN KEY (budget_id)
        REFERENCES public.budgets (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkm5qlang2cio94kb3heobpbydc FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.budget_categories
    OWNER to postgres;